import { ArrowDown, ArrowUp, CircleDot, Network, Route } from "lucide-react";

type Status = "operational" | "degraded" | "overloaded" | "failed" | "recovering";
type Asset = { id: string; name: string; category: string; district: string; population: number; detail: string };
type Link = { source: string; target: string; kind: "dependency" | "transport"; alternateRoutes: number; emergencyPriority?: boolean };

type Props = { selected: Asset | null; assets: Asset[]; links: Link[]; statusById: Record<string, Status>; onSelect: (id: string) => void };
const statusText: Record<Status, string> = { operational: "OPERATIONAL", degraded: "DEGRADED", overloaded: "OVERLOADED", failed: "FAILED", recovering: "RECOVERING" };

export function DependencyInspector({ selected, assets, links, statusById, onSelect }: Props) {
  if (!selected) return <section className="panel dependency-panel empty-dependency"><div className="section-kicker"><Network size={13} /> DEPENDENCY INSPECTOR</div><h2>Select an asset to trace its network position</h2><p>Choose any modeled asset to see direct upstream suppliers, downstream services, and the links that connect them.</p><select className="dependency-picker" aria-label="Choose an asset to inspect" defaultValue="" onChange={(event) => event.target.value && onSelect(event.target.value)}><option value="" disabled>Choose an asset to inspect</option>{assets.filter((asset) => asset.category !== "POPULATION").map((asset) => <option key={asset.id} value={asset.id}>{asset.name} · {asset.category}</option>)}</select></section>;
  const upstream = links.filter((link) => link.target === selected.id).map((link) => ({ link, asset: assets.find((asset) => asset.id === link.source) })).filter((item): item is { link: Link; asset: Asset } => Boolean(item.asset));
  const downstream = links.filter((link) => link.source === selected.id).map((link) => ({ link, asset: assets.find((asset) => asset.id === link.target) })).filter((item): item is { link: Link; asset: Asset } => Boolean(item.asset));
  const renderItem = (item: { link: Link; asset: Asset }) => <button className="dependency-item" key={`${item.link.source}-${item.link.target}`} onClick={() => onSelect(item.asset.id)}><span className={`dependency-status ${statusById[item.asset.id] === "failed" ? "failed" : statusById[item.asset.id] === "operational" ? "operational" : "degraded"}`}><CircleDot size={12} /></span><span className="dependency-copy"><strong>{item.asset.name}</strong><small>{item.asset.category} · {statusText[statusById[item.asset.id]]}</small></span><span className="dependency-link-meta">{item.link.kind === "transport" ? <Route size={12} /> : <Network size={12} />}{item.link.alternateRoutes} alt.</span></button>;
  return <section className="panel dependency-panel"><div className="panel-head compact-head"><div><div className="section-kicker"><Network size={13} /> DEPENDENCY INSPECTOR · CALCULATED PATHS</div><h2>{selected.name}</h2></div><span className="dependency-district">{selected.district} · {statusText[statusById[selected.id]]}</span></div><p className="panel-description">Direct graph neighbors from the current dependency model. Click a neighbor to continue tracing.</p><div className="dependency-grid"><div className="dependency-column"><div className="dependency-heading"><ArrowUp size={14} /> UPSTREAM SUPPLIERS <span>{upstream.length}</span></div>{upstream.length ? upstream.map(renderItem) : <div className="dependency-empty">No modeled upstream supplier</div>}</div><div className="dependency-center"><div className="dependency-center-node"><CircleDot size={17} /><strong>{selected.name}</strong><small>{selected.category} · {selected.district}</small></div><div className="dependency-counts"><span>{upstream.length} upstream</span><span>{downstream.length} downstream</span></div></div><div className="dependency-column"><div className="dependency-heading"><ArrowDown size={14} /> DOWNSTREAM SERVICES <span>{downstream.length}</span></div>{downstream.length ? downstream.map(renderItem) : <div className="dependency-empty">No modeled downstream service</div>}</div></div></section>;
}
